config_version = 7

[accessibility]
ui_scale = 1.300000011920929

[bar]
order = [ "widgets" ]

    [bar.widgets]
    margin_ends = 0
    position = "left"
    scale = 1.7000000178813934
    thickness = 40

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
enabled = false
position = "right"
reserve_space = false
smart_auto_hide = true

[shell]
font_family = "Anka/Coder"
setup_wizard_enabled = false  
launch_apps_as_systemd_services = false # launch apps as transient systemd services (needs Noctalia to be a user unit)

    [shell.panel]
    launcher_position = "auto"

    [shell.screen_corners]
    enabled = true

	[shell.launcher.dmenu.entry.commands]
	command = "fd --full-path $HOME -t f -e pdf"
	exec = "zathura \"$HOME/{selection}\""
	global = false
	glyph = "terminal"
	label = "Open Documents"
	prefix = "doc"

[theme]
builtin = "Catppuccin"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[keybinds]
down = [ "Tab" ]
tab_next = [ "Down" ]
tab_previous = [ "Up" ]
up = [ "Shift+ISO_Left_Tab" ]
