# Colors
include ./colors.conf

# Fonts
font_family	AnkaCoder-r
italic_font	AnkaCoder-i
bold_font	AnkaCoder-b
bold_italic_font AnkaCoder-bi
font_size	12.0

adjust_line_height 0
adjust_column_width 0
box_drawing_scale 0.001, 1, 1.5, 2

# Cursor
cursor_shape	underline
cursor_blink_interval	0
cursor_stop_blinking_after	15.0

# Window
remember_window_size   no
initial_window_width   1050
initial_window_height  900
window_border_width 0
window_margin_width 0.0
window_padding_width 20.0
inactive_text_alpha 1.0
background_opacity 0.96
background_image bg.png
#background_image_layout scale
#background_image_linear no
dynamic_background_opacity yes

# Keys
map ctrl+shift+v        paste_from_clipboard
map ctrl+shift+s        paste_from_selection
map ctrl+shift+c        copy_to_clipboard

map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

map ctrl+shift+a>l set_background_opacity -0.1
map ctrl+shift+a>m set_background_opacity +0.1
